module.exports = [
  // ========== Common (C) ==========
  {
    id: 'strawberry',
    name: 'Strawberry',
    rarity: 'C',
    chance: 3,
    price: 1,
    file: 'Cstrawberry.png',
    description: 'Клубника — королева летних ягод с полей и садов.',
    origin: 'Европа, Северная Америка',
    season: 'Лето',
    edible: true
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    rarity: 'C',
    chance: 6,
    price: 3,
    file: 'Cblueberry.png',
    description: 'Голубика — сочная ягода горных лугов и болот.',
    origin: 'Северная Америка',
    season: 'Лето',
    edible: true
  },
  {
    id: 'blackberry',
    name: 'Blackberry',
    rarity: 'C',
    chance: 12,
    price: 5,
    file: 'Cblackberry.png',
    description: 'Ежевика — растёт на колючих кустах в лесах умеренного климата.',
    origin: 'Европа, Азия',
    season: 'Лето-Осень',
    edible: true
  },
  {
    id: 'cranberry',
    name: 'Cranberry',
    rarity: 'C',
    chance: 20,
    price: 8,
    file: 'Cclanberry.png',
    description: 'Клюква — кислая ягода болотных топей.',
    origin: 'Северная Америка',
    season: 'Осень',
    edible: true
  },
  {
    id: 'raspberry',
    name: 'Raspberry',
    rarity: 'C',
    chance: 44,
    price: 18,
    file: 'Craspberry.png',
    description: 'Малина — душистая ягода садов и лесных опушек.',
    origin: 'Европа',
    season: 'Лето',
    edible: true
  },
  {
    id: 'gooseberry',
    name: 'Gooseberry',
    rarity: 'C',
    chance: 77,
    price: 30,
    file: 'Ugooseberry.png',
    description: 'Крыжовник — колючая ягода деревенских заборов.',
    origin: 'Европа, Западная Азия',
    season: 'Лето',
    edible: true
  },

  // ========== Uncommon (U) ==========
  {
    id: 'foxberry',
    name: 'Foxberry',
    rarity: 'U',
    chance: 101,
    price: 40,
    file: 'Ufoxberry.png',
    description: 'Лисья ягода — хитрая обитательница туманных пустошей.',
    origin: 'Скандинавия',
    season: 'Осень',
    edible: false
  },
  {
    id: 'bilberry',
    name: 'Bilberry',
    rarity: 'U',
    chance: 228,
    price: 90,
    file: 'Ubilberry.png',
    description: 'Черника — целебная ягода тёмных хвойных лесов.',
    origin: 'Северная Европа',
    season: 'Лето',
    edible: true
  },
  {
    id: 'barberry',
    name: 'Barberry',
    rarity: 'U',
    chance: 444,
    price: 175,
    file: 'Ubarberry.png',
    description: 'Барбарис — терпкая ягода горных склонов.',
    origin: 'Центральная Азия',
    season: 'Осень',
    edible: true
  },
  {
    id: 'elderberry',
    name: 'Elderberry',
    rarity: 'U',
    chance: 999,
    price: 400,
    file: 'Uelderberry.png',
    description: 'Бузина — таинственная ягода старых лесов.',
    origin: 'Европа',
    season: 'Осень',
    edible: true
  },
  {
    id: 'mulberry',
    name: 'Mulberry',
    rarity: 'U',
    chance: 1024,
    price: 410,
    file: 'Umulberry.png',
    description: 'Шелковица — сладкая ягода южных садов и аллей.',
    origin: 'Китай',
    season: 'Лето',
    edible: true
  },
  {
    id: 'cloudberry',
    name: 'Cloudberry',
    rarity: 'U',
    chance: 1333,
    price: 530,
    file: 'Ucloudberry.png',
    description: 'Морошка — золотая ягода северных болот и тундры.',
    origin: 'Арктика, Скандинавия',
    season: 'Лето',
    edible: true
  },

  // ========== Rare (R) ==========
  {
    id: 'boysenberry',
    name: 'Boysenberry',
    rarity: 'R',
    chance: 2111,
    price: 850,
    file: 'Rboysenberry.png',
    description: 'Бойзенова ягода — гибрид, рождённый в тайных лабораториях ботаников.',
    origin: 'Калифорния, США',
    season: 'Лето',
    edible: true
  },
  {
    id: 'marionberry',
    name: 'Marionberry',
    rarity: 'R',
    chance: 3800,
    price: 1500,
    file: 'Rmarionberry.png',
    description: 'Мэрионберри — жемчужина Орегонских ферм.',
    origin: 'Орегон, США',
    season: 'Лето',
    edible: true
  },
  {
    id: 'loganberry',
    name: 'Loganberry',
    rarity: 'R',
    chance: 6666,
    price: 2600,
    file: 'Rloganberry.png',
    description: 'Логанова ягода — случайный гибрид из калифорнийских садов.',
    origin: 'Калифорния, США',
    season: 'Лето',
    edible: true
  },
  {
    id: 'huckleberry',
    name: 'Huckleberry',
    rarity: 'R',
    chance: 9100,
    price: 3600,
    file: 'Rhuckleberry.png',
    description: 'Хаклберри — дикая ягода горных троп Америки.',
    origin: 'Горы Северной Америки',
    season: 'Лето-Осень',
    edible: true
  },
  {
    id: 'tayberry',
    name: 'Tayberry',
    rarity: 'R',
    chance: 10101,
    price: 4000,
    file: 'Rtayberry.png',
    description: 'Тайберри — шотландский гибрид с берегов реки Тей.',
    origin: 'Шотландия',
    season: 'Лето',
    edible: true
  },
  {
    id: 'dewberry',
    name: 'Dewberry',
    rarity: 'R',
    chance: 16000,
    price: 6400,
    file: 'Rdewberry.png',
    description: 'Росяника — ягода, рождённая из утренней росы лесных полян.',
    origin: 'Северная Америка',
    season: 'Лето',
    edible: true
  },

  // ========== Epic (E) ==========
  {
    id: 'bayberry',
    name: 'Bayberry',
    rarity: 'E',
    chance: 28888,
    price: 11500,
    file: 'Ebayberry.png',
    description: 'Восковница — ягода прибрежных скал с восковым налётом.',
    origin: 'Атлантическое побережье',
    season: 'Осень',
    edible: false
  },
  {
    id: 'serviceberry',
    name: 'Serviceberry',
    rarity: 'E',
    chance: 32000,
    price: 12800,
    file: 'Eserviceberry.png',
    description: 'Ирга — сладкая ягода, цветущая раньше всех в весеннем лесу.',
    origin: 'Северная Америка',
    season: 'Лето',
    edible: true
  },
  {
    id: 'bearberry',
    name: 'Bearberry',
    rarity: 'E',
    chance: 44444,
    price: 17800,
    file: 'Ebearberry.png',
    description: 'Медвежья ягода — любимое лакомство медведей в горных лесах.',
    origin: 'Арктика, горные леса',
    season: 'Осень',
    edible: false
  },
  {
    id: 'wolfberry',
    name: 'Wolfberry',
    rarity: 'E',
    chance: 67000,
    price: 26800,
    file: 'Ewolfberry.png',
    description: 'Волчья ягода — опасная красавица тёмных чащоб.',
    origin: 'Восточная Азия',
    season: 'Осень',
    edible: false
  },
  {
    id: 'pokeberry',
    name: 'Pokeberry',
    rarity: 'E',
    chance: 90909,
    price: 36400,
    file: 'Epokeberry.png',
    description: 'Лаконос — ядовитая ягода с мистической фиолетовой кровью.',
    origin: 'Восточная Америка',
    season: 'Осень',
    edible: false
  },
  {
    id: 'chokeberry',
    name: 'Chokeberry',
    rarity: 'E',
    chance: 121212,
    price: 48500,
    file: 'Echokeberry.png',
    description: 'Черноплодная рябина — горькая ягода заброшенных опушек.',
    origin: 'Восточная Америка',
    season: 'Осень',
    edible: true
  },

  // ========== Legendary (L) ==========
  {
    id: 'hollyberry',
    name: 'Hollyberry',
    rarity: 'L',
    chance: 200000,
    price: 80000,
    file: 'Lhollyberry.png',
    description: 'Падуб — рождественская ягода, оберег от злых духов.',
    origin: 'Европа, Западная Азия',
    season: 'Зима',
    edible: false
  },
  {
    id: 'mistletoeberry',
    name: 'Mistletoeberry',
    rarity: 'L',
    chance: 320320,
    price: 128000,
    file: 'Lmistleberry.png',
    description: 'Омела — паразитическая ягода, растущая между небом и землёй.',
    origin: 'Европа',
    season: 'Зима',
    edible: false
  },
  {
    id: 'bunchberry',
    name: 'Bunchberry',
    rarity: 'L',
    chance: 467674,
    price: 187000,
    file: 'Lbunchberry.png',
    description: 'Кизил канадский — крохотная звёздочка северных хвойных лесов.',
    origin: 'Канада',
    season: 'Осень',
    edible: true
  },
  {
    id: 'snowberry',
    name: 'Snowberry',
    rarity: 'L',
    chance: 660606,
    price: 264000,
    file: 'Lsnowberry.png',
    description: 'Снежноягодник — призрачная ягода зимних садов.',
    origin: 'Северная Америка',
    season: 'Зима',
    edible: false
  },
  {
    id: 'sea_buckthornberry',
    name: 'Sea-Buckthornberry',
    rarity: 'L',
    chance: 888000,
    price: 355000,
    file: 'Lsea-buckthornberry.png',
    description: 'Облепиха — золотое сокровище морских берегов.',
    origin: 'Евразия',
    season: 'Осень',
    edible: true
  },
  {
    id: 'rowanberry',
    name: 'Rowanberry',
    rarity: 'L',
    chance: 1000001,
    price: 400000,
    file: 'Lrowanberry.png',
    description: 'Рябина — огненная гроздь магических деревьев.',
    origin: 'Европа, Сибирь',
    season: 'Осень',
    edible: true
  },

  // ========== Mythic (M) ==========
  {
    id: 'acaiberry',
    name: 'Acai Berry',
    rarity: 'M',
    chance: 1606060,
    price: 640000,
    file: 'Macaiberry.png',
    description: 'Асаи — суперфуд из глубин амазонских джунглей.',
    origin: 'Амазония, Бразилия',
    season: 'Круглый год',
    edible: true
  },
  {
    id: 'youngberry',
    name: 'Youngberry',
    rarity: 'M',
    chance: 2222222,
    price: 890000,
    file: 'Myoungberry.png',
    description: 'Янгберри — вечно молодая ягода тропических островов.',
    origin: 'Тропические острова',
    season: 'Лето',
    edible: true
  },
  {
    id: 'silvanberry',
    name: 'Silvanberry',
    rarity: 'M',
    chance: 3600000,
    price: 1440000,
    file: 'Msilvanberry.png',
    description: 'Сильванберри — лесной дух в ягодной форме.',
    origin: 'Древние леса Европы',
    season: 'Лето',
    edible: true
  },
  {
    id: 'strasberry',
    name: 'Strasberry',
    rarity: 'M',
    chance: 4777777,
    price: 1910000,
    file: 'Mstrasberry.png',
    description: 'Страсберри — аномальная мутация с космическим вкусом.',
    origin: 'Неизвестно',
    season: 'Весна',
    edible: true
  },
  {
    id: 'whiteberry',
    name: 'Whiteberry',
    rarity: 'M',
    chance: 6606066,
    price: 2640000,
    file: 'Mwhiteberry.png',
    description: 'Белая ягода — альбинос ягодного мира, растёт при лунном свете.',
    origin: 'Лунные долины',
    season: 'Весна',
    edible: true
  },
  {
    id: 'juneberry',
    name: 'Juneberry',
    rarity: 'M',
    chance: 9999999,
    price: 4000000,
    file: 'Mjuneberry.png',
    description: 'Июньская ягода — плод, являющийся с первым летним теплом.',
    origin: 'Прерии Северной Америки',
    season: 'Лето',
    edible: true
  },

  // ========== Cosmic (CS) ==========
  {
    id: 'white_baneberry',
    name: 'White Baneberry',
    rarity: 'CS',
    chance: 16666666,
    price: 6650000,
    file: 'CSwhite-baneberry.png',
    description: 'Кукольный глаз — жуткая ягода с глазоподобным видом из проклятых рощ.',
    origin: 'Проклятые рощи',
    season: 'Осень',
    edible: false
  },
  {
    id: 'blue_sausageberry',
    name: 'Blue Sausageberry',
    rarity: 'CS',
    chance: 24000000,
    price: 9600000,
    file: 'CSblue-sausageberry.png',
    description: 'Голубая сосисочная ягода — инопланетная форма жизни из метеоритных кратеров.',
    origin: 'Метеоритные кратеры',
    season: 'Неизвестен',
    edible: false
  },
  {
    id: 'halafruit_berry',
    name: 'Halafruit Berry',
    rarity: 'CS',
    chance: 31010101,
    price: 12400000,
    file: 'CShalafruitberry.png',
    description: 'Халафрукт — светящаяся ягода из параллельного измерения.',
    origin: 'Параллельное измерение',
    season: 'Неизвестен',
    edible: false
  },
  {
    id: 'balloon_berry',
    name: 'Balloon Berry',
    rarity: 'CS',
    chance: 44044044,
    price: 17600000,
    file: 'CSballoonberry.png',
    description: 'Воздушная ягода — невесомый плод, парящий над облачными вершинами.',
    origin: 'Облачные вершины',
    season: 'Неизвестен',
    edible: false
  },
  {
    id: 'five_flavor_berry',
    name: 'Five-Flavor Berry',
    rarity: 'CS',
    chance: 67676767,
    price: 27000000,
    file: 'CSfive-flavorberry.png',
    description: 'Ягода пяти вкусов — меняет вкус при каждом укусе.',
    origin: 'Мистические сады',
    season: 'Неизвестен',
    edible: true
  },

  // ========== Secret (S) ==========
  {
    id: 'teaberry',
    name: 'Teaberry',
    rarity: 'S',
    chance: 100000000,
    price: 40000000,
    file: 'Steaberry.png',
    description: 'Чайная ягода — легендарная ягода, о которой слагают мифы. Растёт раз в тысячу лет на вершине Мировой горы.',
    origin: 'Вершина Мировой горы',
    season: 'Раз в 1000 лет',
    edible: true
  },
  {
    id: 'starberry',
    name: 'Starberry',
    rarity: 'S',
    chance: 999000999,
    price: 500000000,
    file: 'Sstarberry.png',
    description: 'Звёздная ягода — рождается из падающих звёзд, светится в темноте вечным светом.',
    origin: 'Звёздное небо',
    season: 'Звездопад',
    edible: true
  },

  // ========== Abuse Secret (AS) — only during events ==========
  {
    id: 'pokyku',
    name: 'Pokyku',
    rarity: 'AS',
    chance: 111111111,
    price: 50000000,
    file: 'ASpokyku.png',
    description: 'Покику — ягода богов.',
    origin: 'Разлом реальности',
    season: 'Ивент ABUSE',
    edible: false
  },
  {
    id: 'sixseven',
    name: 'SixSeven',
    rarity: 'AS',
    chance: 75000000,
    price: 75000000,
    file: 'ASsixseven.png',
    description: 'Сикссевен — сикссевен сикссевен сикссевен.',
    origin: 'Числовая пустота',
    season: 'Ивент ABUSE',
    edible: false
  },
// ========== Secret (S) — Продолжение ==========
  {
    id: 'partridgeberry',
    name: 'Partridgeberry',
    rarity: 'S',
    chance: 244000000,
    price: 95000000,
    file: 'Spartridgeberry.png',
    description: 'Митровидка — скрытная ягода, маскирующаяся под перья лесных птиц.',
    origin: 'Хвойные подлески',
    season: 'Осень',
    edible: true
  },
  {
    id: 'baneberry',
    name: 'Baneberry',
    rarity: 'S',
    chance: 499099099,
    price: 195000000,
    file: 'Sbaneberry.png',
    description: 'Воронец — кроваво-красный предвестник опасности. Красив, но крайне ядовит.',
    origin: 'Теневые дубравы',
    season: 'Лето',
    edible: false
  },
  {
    id: 'deerberry',
    name: 'Deerberry',
    rarity: 'S',
    chance: 777077077,
    price: 310000000,
    file: 'Sdeerberry.png',
    description: 'Оленья ягода — благословенный плод, растущий только там, где ступала нога духа лесов.',
    origin: 'Священные рощи',
    season: 'Круглый год',
    edible: true
  },
  {
    id: 'fireberry',
    name: 'Fireberry',
    rarity: 'S',
    chance: 6666666666,
    price: 2600000000,
    file: 'Sfireberry.png',
    description: 'Адская земляника — объята вечным пламенем. Заставляет кровь закипать от одного запаха.',
    origin: 'Подземные тектонические разломы',
    season: 'Полночь',
    edible: true
  },
  {
    id: 'pearlmistberry',
    name: 'Pearlmistberry',
    rarity: 'S',
    chance: 12000000000,
    price: 4800000000,
    file: 'Spearlmistberry.png',
    description: 'Жемчужная капля — идеальная сфера, внутри которой клубится осязаемый розовый туман.',
    origin: 'Туманные фьорды',
    season: 'Рассвет',
    edible: true
  },
  {
    id: 'gemberry',
    name: 'Gemberry',
    rarity: 'S',
    chance: 28000000000,
    price: 11000000000,
    file: 'Sgemberry.png',
    description: 'Изумрудный куб — кристаллическая твердая ягода, пульсирующая концентрированной магией земли.',
    origin: 'Древние шахты гномов',
    season: 'Зима',
    edible: false
  },
  {
    id: 'anglerfishberry',
    name: 'Anglerfishberry',
    rarity: 'S',
    chance: 67000000000,
    price: 26500000000,
    file: 'Sanglerfishberry.png',
    description: 'Глубоководный удильщик — зубастая плотоядная ягода. Сама охотится на неосторожных сборщиков.',
    origin: 'Марианская впадина',
    season: 'Неизвестен',
    edible: false
  },
  {
    id: 'steampunkberry',
    name: 'Steampunkberry',
    rarity: 'S',
    chance: 89000000000,
    price: 35000000000,
    file: 'Ssteampunkberry.png',
    description: 'Стимпанк-тыковка — механический латунный плод, шуршащий шестеренками и выпускающий пар.',
    origin: 'Заброшенные заводы викторианской эпохи',
    season: 'Осень',
    edible: false
  },
  {
    id: 'clockberry',
    name: 'Clockberry',
    rarity: 'S',
    chance: 128000000000,
    price: 51000000000,
    file: 'Sclockberry.png',
    description: 'Хроно-ягода — её стрелки тикают в такт биения сердца вселенной. Способна искажать время.',
    origin: 'Временная петля',
    season: 'Вне времени',
    edible: true
  },
  {
    id: 'voidberry',
    name: 'Voidberry',
    rarity: 'S',
    chance: 333000000000,
    price: 133000000000,
    file: 'Svoidberry.png',
    description: 'Ягода бездны — поглощает свет вокруг себя и оставляет за собой шлейф фиолетового дыма.',
    origin: 'Черные дыры',
    season: 'Космическая ночь',
    edible: false
  },
  {
    id: 'shroomberry',
    name: 'Shroomberry',
    rarity: 'S',
    chance: 767000000000,
    price: 305000000000,
    file: 'Sshroomberry.png',
    description: 'Шрумберри — биолюминесцентный гибрид древнего гриба и сочной неоновой ягоды.',
    origin: 'Пещеры светящихся спор',
    season: 'Ночь',
    edible: true
  },
  {
    id: 'cosmicberry',
    name: 'Cosmicberry',
    rarity: 'S',
    chance: 1200000000000,
    price: 480000000000,
    file: 'Scosmicberry.png',
    description: 'Космический вихрь — полупрозрачная оболочка, внутри которой вращается настоящая мини-галактика.',
    origin: 'Центр Млечного Пути',
    season: 'Звездопад',
    edible: true
  },
  {
    id: 'deepmossberry',
    name: 'Deepmossberry',
    rarity: 'S',
    chance: 2880000000000,
    price: 1150000000000,
    file: 'Sdeepmossberry.png',
    description: 'Дипмоссберри — скрывается под толщей ядовитого мха на дне древних мертвых топей.',
    origin: 'Ведьмины болота',
    season: 'Осень',
    edible: false
  },
  {
    id: 'serpenberry',
    name: 'Serpenberry',
    rarity: 'S',
    chance: 6660000000000,
    price: 2660000000000,
    file: 'Sserpenberry.png',
    description: 'Змеиная ягода — покрыта чешуей и свернута кольцом. Издает едва слышное зловещее шипение.',
    origin: 'Гнезда Исполинских Змей',
    season: 'Лето',
    edible: false
  },

  // ========== Godly (G) ==========
  {
    id: 'snowflakeberry',
    name: 'Snowflakeberry',
    rarity: 'G',
    chance: 100000000000000,
    price: 40000000000000,
    file: 'Gsnowflakeberry.png',
    description: 'Снежинка — божественно хрупкий плод абсолютного нуля. Рассыпается от теплого взгляда.',
    origin: 'Чертоги Ледяных Богов',
    season: 'Вечная зима',
    edible: true
  },
  {
    id: 'goldprismberry',
    name: 'Goldprismberry',
    rarity: 'G',
    chance: 999000000000000,
    price: 400000000000000,
    file: 'Ggoldprismberry.png',
    description: 'Золотая призма — венец творения ягодного мира. Её идеальные золотые грани отражают судьбы вселенной.',
    origin: 'Исток Первородного Света',
    season: 'Эра Просвещения',
    edible: true
  }
];
